name = "artistic-portal"
main = "worker/index.js"
compatibility_date = "2026-01-16"

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = true

[observability]
[observability.logs]
enabled = false
invocation_logs = true
